session:
  timeout: 180
  auth: false
server:
  port=8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/snwltest?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: 
       - classpath:sql/createtable.sql
    initialization-mode: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
  
logging:
  level:
     com.suineng.dao : ERROR

account:
    key: 1234567890
    name: admin
    passwd: admin
     
login:
    uri: /login/auth.html
    index: /login
    
alert:
    times: 2
    period: 3600
    config: E:\project\4.30\smoke\alert\threshold.json
model:
    config: E:\project\4.30\smoke\model\model.properties
    host: tcp://192.168.1.107:61613
    read: true
    userName: admin
    passWord: password
    topic: UPDATA

test:
    insert: false